### ISSUE TITLE
Stupid question

### ISSUE THREAD

**Issue by SomeITGuys** [phage-nz/iisfortify-ps#1]
Stupid question,
I see this script adds the security pieces to the default IIS pool/site on the server, if you have a multi-tenant web server (with 50 IIS sites) this does not take effect on any other IIS sites on the server?

Unless I am missing something, running this and subsequent security scans still show the vulnerabilities.

Thanks!

**Comment by phage-nz** [comment]
The headers are created at the root of the IIS server so apply to all sites. Response Headers are an inheritable configuration. If you have 50 sites on the server then I'd apply them with some level of care. Items like X-Frame-Options or the application of Strict-Transport-Security to subdomains may need to be more open.

Goes without saying you should roll this out to a dev server first.

**Comment by SomeITGuys** [comment]
Thanks for the quick response! Figured it out, it was due to </clear> tags in the web.configs. In case anyone else runs into this - https://forums.iis.net/t/1237726.aspx?HTTP+Response+Headers+Not+Getting+Inherited+By+All+Sites+IIS+8+5

**Comment by phage-nz** [comment]
Yep, they won't inherit if there are overriding tags or a clear.

Thanks.
